export const pricingList = [
    {
        id: 1,
        title: 'Subsidi',
        harga: 150,
        isRecommended: false,
        website: true,
        music: true,
        detail: true,
        maps: true,
        amplop: true,
        gallery: '3 Foto',
        countdown: false,
        story: false,
        spv: false,
        doa: false,
        inviteLink: false,
        qr: false
    },
    {
        id: 2,
        title: 'Hemat',
        harga: 200,
        isRecommended: true,
        website: true,
        music: true,
        detail: true,
        maps: true,
        amplop: true,
        gallery: '7 Foto 1 Video',
        countdown: true,
        story: true,
        spv: true,
        doa: false,
        inviteLink: false,
        qr: false
    },
    {
        id: 3,
        title: 'Biasa',
        harga: 230,
        isRecommended: false,
        website: true,
        music: true,
        detail: true,
        maps: true,
        amplop: true,
        gallery: '10 Foto 3 Video',
        countdown: true,
        story: true,
        spv: true,
        doa: true,
        inviteLink: 100,
        qr: false
    },
    {
        id: 4,
        title: 'Orang Kaya',
        harga: 350,
        isRecommended: false,
        website: true,
        music: true,
        detail: true,
        maps: true,
        amplop: true,
        gallery: '15 Foto 5 Video',
        countdown: true,
        story: true,
        spv: true,
        doa: true,
        inviteLink: 200,
        qr: false
    },
    {
        id: 5,
        title: 'Sultan',
        harga: 400,
        isRecommended: false,
        website: true,
        music: true,
        detail: true,
        maps: true,
        amplop: true,
        gallery: '20 Foto 5 Video',
        countdown: true,
        story: true,
        spv: true,
        doa: true,
        inviteLink: 400,
        qr: 400
    },
];